### ISSUE TITLE
NullReferenceException when trying to run app

### ISSUE THREAD

**Issue by Orgbrat** [maxkoshevoi/XCTLocalizationDemo#1]
So I downloaded the code and tried to run the project in UWP and I app getting a NullReferenceException stating AppDescription does not exist. But I can see that it does in both resx files.  The solution builds successfully but won't run because of the error. Wanted to see how this all works. Do you have any idea why this is crashing?

**Comment by maxkoshevoi** [comment]
Thanks for reporting this! I only tested it on Android, and assumed it will work on other platforms (since this app doesn't have any platform specific code).

Turns out UWP needs to have natural language specified: https://stackoverflow.com/questions/47287419/xamarin-forms-uwp-with-netstandard-2-0-and-null-resources

Fixed the issue. Everything should work now.

**Comment by Orgbrat** [comment]
Every does work now. Thanks for the quick response and effort.
